replicaCount: ${replica_count}

fullnameOverride: ${fullnameOverride}
namespace: ${namespace}

# containerSpecOptions:
#   securityContext:
#     runAsUser: 1000
#     runAsGroup: 1000

deployment:
  containers:
  - name: ${fullnameOverride}
    image:
      repository: ${docker_repository}
      tag: ${docker_tag}
      pullPolicy: Always

    ports:
    - name: http
      protocol: TCP
      containerPort: 80
      servicePort: 80

    resources:
      requests:
        memory: ${requests_memory}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-external
    # kubernetes.io/tls-acme: "true"
  paths:
    - path: /
      servicePort: http
  hosts:
    - admin.dev.yourgem.app
    - admin.dev.pearl.app
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
