# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - "*_stage"
    paths-ignore:
      - 'terraform-environments/**'
  pull_request:
    branches:
      - 'main'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Docker container build and push
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY_NAME_DEV: 067550988196.dkr.ecr.us-east-1.amazonaws.com/frontend
      DOCKER_REPOSITORY_NAME_STAGE: 283278994941.dkr.ecr.us-east-1.amazonaws.com/frontend
    steps:
      # Checking out multilple repo side by side
      # https://github.com/actions/checkout#checkout-multiple-repos-private
      - name: Checkout
        uses: actions/checkout@v2

      # Docs: https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md
      - name: Dev - Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.DOCKER_REPOSITORY_NAME_DEV }}
      - name: Dev - Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Dev - Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Dev - Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Dev - Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Dev - Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            environment=pearl-dev
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Dev - Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Stage - Docker meta
        id: meta-staging
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.DOCKER_REPOSITORY_NAME_STAGE }}
      - name: Stage - Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Stage - Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Stage - Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGE }}
          aws-region: us-east-1

      - name: Stage - Login to Amazon ECR
        id: login-ecr-staging
        uses: aws-actions/amazon-ecr-login@v1

      - name: Stage - Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args:
            environment=pearl-prod
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-staging.outputs.tags }}
          labels: ${{ steps.meta-staging.outputs.labels }}

      - name: Stage - Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


  ## Deploy to dev
  ## Will only run on a tag release: v*
  ## Will update the dev's TF file's docker tag with the tag and commit it back into the 'main' branch
  ## This will trigger a TF run to apply the changes
  trigger-deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && !endsWith(github.ref, '_stage')
    steps:
    # Including the PERSONAL_ACCESS_TOKEN_CORE in the checkout.  Without this the
    # following stefanzweifel/git-auto-commit-action will not trigger a
    # new github action for deployment
    # doc: https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN_CORE }}
        ref: 'main'

    - name: Extract tag var
      id: tag_id
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    # Update the docker tags in the TF/helm deployment
    - name: Update dev image tag
      uses: jacobtomlinson/gha-find-replace@0.1.4
      with:
        find: "docker_tag        = \".*\""
        replace: "docker_tag        = \"${{ steps.tag_id.outputs.tag }}\""
        include: "terraform-environments/aws/dev/helm/70-gem-frontend/main.tf"

    - name: Check output
      run: |
        echo "ref: ${{ github.ref }}"
        echo "head_ref: ${{ github.head_ref }}"
        echo "base_ref: ${{ github.base_ref }}"
        echo ${{ steps.tag_id.outputs.tag }}
        cat terraform-environments/aws/dev/helm/70-gem-frontend/main.tf

    - name: Update dev deploy docker tags file
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Automated Change | Deploy to dev | tags: ${{ steps.tag_id.outputs.tag }}"
        file_pattern: terraform-environments/*
