name: Workflow Build

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      docker_meta_tags:
        required: false
        type: string
        default: ''
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCESS_KEY_ID_STAGE:
        required: true
      AWS_SECRET_ACCESS_KEY_STAGE:
        required: true
      PASSWORD:
        required: true

jobs:
  build:
    name: Build

    strategy:
      matrix:
        environment_name:
          - dev
          - stage
        include:
          - environment_name: dev
            docker_repository_name: 067550988196.dkr.ecr.us-east-1.amazonaws.com
            aws_access_key_id_secrets_name: AWS_ACCESS_KEY_ID
            aws_secret_access_key_secrets_name: AWS_SECRET_ACCESS_KEY
          - environment_name: stage
            docker_repository_name: 283278994941.dkr.ecr.us-east-1.amazonaws.com
            aws_access_key_id_secrets_name: AWS_ACCESS_KEY_ID_STAGE
            aws_secret_access_key_secrets_name: AWS_SECRET_ACCESS_KEY_STAGE

    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets[matrix.aws_access_key_id_secrets_name] }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets[matrix.aws_secret_access_key_secrets_name] }}
    steps:
      # Checking out multiple repo side by side
      # https://github.com/actions/checkout#checkout-multiple-repos-private
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      # Docs: https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: ${{ matrix.docker_repository_name }}/${{ inputs.service_name }}
          tags: ${{ inputs.docker_meta_tags }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./main
          file: ./main/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            gh_password=${{ secrets.PASSWORD }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
